string = "Divyaaaaaaaaaaaansh"
print(string.endswith("sh"))
print(string.startswith("D"))
print(string.find("v"))
print(string.replace("v", "V"))
print(string.upper())
print(string.lower())
print(string.capitalize())
print(string.title())
print(string.isalpha())
print(string.isdigit())
print(string.isalnum())
print(string.islower())
print(string.isupper())
print(string.isnumeric())
print(string.isidentifier())
print(string.isprintable())
print(string.strip())
print(string.lstrip())
print(string.rstrip())
print(string.split("i"))
print(string.join(["Hello", "World"]))
print(string.count("i"))
print(string.center(20, "*"))
print(string.ljust(20, "-"))
print(string.rjust(20, "-"))
print(string.zfill(20))
print(string.swapcase())
print(string.partition("v"))
print(string.rpartition("v"))
print(string.splitlines())
print(string.translate(str.maketrans("v", "V")))
print(string.format("Hello, {}!", string))
print(string.format_map({"name": string}))
print(string.replace("a", "A"))


#If u use string all functions, it will not change the main string, since its immutable. it will create a new string and return it.